export const productList =[
    {
        id: '1',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
    {
        id: '2',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
    {
        id: '3',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
    {
        id: '4',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
    {
        id: '5',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
    {
        id: '6',
        name: 'Nike KD12',
        title: 'Men\'s Running Shoes',
        des: 'Ensure a comfortable running session by wearing this pair of cool running shoes from Nike.',
        price: 50,
        image: '../assets/images/shoe.png',
    },
]